### ISSUE TITLE
About render（）

### ISSUE THREAD

**Issue by lzhJesus** [Hamme122/gaussian-flow#1]
您好，我看在训练代码中并没有对dddm_model等相关参数的保存，如果我后续通过渲染函数进行渲染，我需要在训练过程中对dddm_model中的哪些必要参数进行保存呢？

**Comment by Hamme122** [comment]
dddm_model相关的参数和Gaussian的属性可以视作等同的，对于渲染来说应该都是必要的，需要修改一下保存的函数加上这一部分

**Comment by lzhJesus** [comment]
> dddm_model相关的参数和Gaussian的属性可以视作等同的，对于渲染来说应该都是必要的，需要修改一下保存的函数加上这一部分

谢谢回复！！
