### ISSUE TITLE
IndexError: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by Wen-Hui-Ma** [Hamme122/gaussian-flow#2]
There is an error while executing the render.py render command (python render.py --model_path “output/dnerf/bouncingballs/” --configs arguments/dnerf/bouncingballs.py) as follows:

Traceback (most recent call last):
  File "render.py", line 124, in <module>
    render_sets(model.extract(args), hyperparam.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.skip_video)
  File "render.py", line 96, in render_sets
    render_set(dataset.model_path, "train", scene.loaded_iter, scene.getTrainCameras(), gaussians, pipeline, background,cam_type)
  File "render.py", line 62, in render_set
    rendering = render(view, gaussians, pipeline, background,cam_type=cam_type)["render"]
  File "/raid/mawenhui/Code/Cache/gaussian-flow/gaussian_renderer/__init__.py", line 95, in render
    time_scaling = torch.clamp(torch.exp(pc._timescaling[:, 0]).view(-1, 1) * time + pc._timescaling[:, 1].view(-1, 1), min=0.01)
IndexError: too many indices for tensor of dimension 1

Have you resolved this error yet? Thank you for your guidance.

**Comment by Hamme122** [comment]
Sorry, I guess this is because I haven't update render.py file, only train.py can be used normally

**Comment by Hamme122** [comment]
And you can refer to the official implementation in https://github.com/NJU-3DV/Gaussian-Flow

**Comment by Wen-Hui-Ma** [comment]
Thank you for your response and clarification!
